### ISSUE TITLE
Save history from server to database

### ISSUE THREAD

**Issue by k-morozov** [k-morozov/App-chat#5]
Save history from server to database (SQLite?)

**Comment by sanketsharma** [comment]
@k-morozov I am interested in working on this.

**Comment by k-morozov** [comment]
@sanketsharma Greetings. It would be cool if you could implement saving the message stories from the server to some database (SQLite for example). The main thing is that when you enable the server can read the message history.
The history is stored in Channel ::history channels.

**Comment by sanketsharma** [comment]
@k-morozov What is the table schema you want me to store the message into? Should it be just a text column named message? Or should I be storing different parts of the message as different columns?

**Comment by k-morozov** [comment]
@sanketsharma Sorry for the long answer.
I'm working on removing the struct Message for data transport now. 
Message exchange will be implemented through Request/Response classes. 
The table will require:
---> | id record | time-date send message | login string sender | loginID sender | roomID where write mes | text message | 
I saw you create Pull-req, but deleted ...
